### ISSUE TITLE
Builtin FBX exporter presets

### ISSUE THREAD

**Issue by akareactor** [BlakeDarrow/EasyExport#18]
It will be very cool to use "Operator presets" from the built-in FBX exporter
![2022-07-12_12-31-35](https://user-images.githubusercontent.com/109142658/178459274-e431aa19-10b5-4e84-8ecc-f0e2cee375cd.png)
!

**Comment by BlakeDarrow** [comment]
Great Idea!

**Comment by BlakeDarrow** [comment]
If I understand your request correctly, I can add the user defined "Operator Presets" to the "Presets" drop-down in EasyExport, shown below. Is this what you are thinking?

![image](https://user-images.githubusercontent.com/71980368/178512574-5eae3487-6e9d-4665-8f27-fc17349624aa.png)

**Comment by akareactor** [comment]
> If I understand your request correctly, I can add the user defined "Operator Presets" to the "Presets" drop-down in EasyExport, shown below. Is this what you are thinking?

Let me explain. I'm using FBX for the different purposes. Exporting meshes, meshes with armature or armature only. Sometimes aplly scaling, setting Up and Forward directions (for Unity, yes!), apply transforms or not. For isolated animation clips, switching a NLA strips flag, leaf bones etc. Setting of necessary parameters is small but very important mindwork.

I'd like to save this mindwork with Easy Export addon, in this case it will be a delightful solution, I believe :)

**Comment by BlakeDarrow** [comment]
I should be able to find a solution! I will get back to you with an update, thank you for the suggestion!

**Comment by BlakeDarrow** [comment]
[EasyExport.zip](https://github.com/BlakeDarrow/EasyExport/files/9099028/EasyExport.zip)

@akareactor I pushed a test build, v1.2.5, which implements the ability to use blenders user defined export presets, along with my tool. (Zip attached above)

To add or remove presets, you have to navigate to File-> Export-> FBX. From their you can create your custom preset and save it. I would recommend always use "Limit to: Selected Objects" when creating a export preset so that you can utilize the batch export of my tool with whatever settings you need.

![image](https://user-images.githubusercontent.com/71980368/178652115-ebce58a1-e0dc-43a1-817d-137634bb8e94.png)

**Comment by akareactor** [comment]
Wow, it's awesome! I just tested and it works, really!

I export FBX to Unity dozens of times per day, and this feature will save a lot of my time! Thank you very much, I'll recommend your tool to all my communities.

A little remark - is it possible to unicode naming? Some presets are in non-latin codepage:

![2022-07-13_10-08-25](https://user-images.githubusercontent.com/109142658/178673705-f53f9712-301a-4b04-b9ac-c4a7f0a60201.jpg)

**Comment by BlakeDarrow** [comment]
[EasyExport.zip](https://github.com/BlakeDarrow/EasyExport/files/9104356/EasyExport.zip)
 
I'm glad to hear it is working, thank you very much!

Latest push to branch has a fix for the unicode naming problem, and a new editable default option. **_If you are still having unicode problems please reach out!_**
